name: Linux-Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install libraries
        run: sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev


      - name: Enable SWRendering
        run: cp src/linux/pom.xml pom.xml

      - name: Gluon Build
        run: mvn -Pdesktop client:build client:package

      - name: Copy native app to zzv-apt-package
        run: |
          mkdir -p src/linux/zzv_1.0.1_amd64/usr/local/bin/;
          cp target/client/x86_64-linux/Zzv-view src/linux/zzv_1.0.1_amd64/usr/local/bin/zzv-view

      - name: Build apt-repository
        run: cd src/linux && bash gpg.sh && bash package.sh
        env: 
          GPG_PASS: ${{ secrets.GPG_PASS }}

      - name: Copy apt repo to staging
        run: cp -r src/linux/zzv-view-apt-repo.zip staging

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
