name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: Apple-Actions/import-codesign-certs@v1
      #   if: ${{ github.repository_owner == 'gluonhq' }} 
      #   with:
      #     p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
      #     p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
      # - uses: Apple-Actions/download-provisioning-profiles@v1
      #   if: ${{ github.repository_owner == 'gluonhq' }} 
      #   with:
      #     bundle-id: be.webtechie.ResistorCalculatorApp
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      # - name: Gluon License
      #   uses: gluonhq/gluon-build-license@v1
      #   with:
      #     gluon-license: ${{ secrets.GLUON_LICENSE }}

      - name: Gluon Compile
        run: mvn -Pios -DskipIOSSigning=${skipIOSSigning} client:compile

      - name: Copy
        # run: cp -r /Users/runner/work/zzv/zzv/target/client/arm64-ios/gensrc/ios/assets/Base.lproj /Users/runner/work/zzv/zzv/src/ios/assets/Base.lproj
        run: ls -lh /Users/runner/work/zzv/zzv/target/client/

      - name: Gluon Build
        run: mvn -Pios -DskipIOSSigning=${skipIOSSigning} client:link client:package


      # - uses: Apple-Actions/upload-testflight-build@master
      #   if: ${{ github.repository_owner == 'gluonhq' }} 
      #   with:
      #     app-path: target/client/arm64-ios/Resistor Calculator.ipa
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
